# ------------------------------------------------------------------------------
#  Copyright Christopher Kormanyos 2025.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# ------------------------------------------------------------------------------

name: mpir
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  msvc-lib_mpir_core2-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone-boost-develop
        working-directory: ${{ runner.workspace }}
        run: |
          git clone -b develop --depth 1 https://github.com/boostorg/boost.git ${{ runner.workspace }}/boost-root
      - name: clone-boost-submods
        working-directory: ${{ runner.workspace }}/boost-root
        run: |
          git submodule update --init tools
          git submodule update --init libs/config
          git submodule update --init libs/multiprecision
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.4
      - name: bootstrap-boost
        working-directory: ${{ runner.workspace }}/boost-root
        run: |
          ./bootstrap.bat
          ./b2 headers
      - name: update-yasm
        shell: cmd
        working-directory: ${{ runner.workspace }}/mpir/build.vc/yasm/1.3.0
        run: |
          del /Q .\yasm.exe
          curl -L -o yasm.exe https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-1.3.0-win64.exe
          echo "Is the YASM download here?"
          dir yasm.exe
      - name: msvc-lib_mpir_core2-x64
        shell: cmd
        working-directory: ./
        run: |
          set PATH=%CD%\build.vc\yasm\1.3.0;%PATH%
          cd build.vc17
          echo "Query YASM version"
          echo.
          yasm.exe --version
          echo.
          dir %CD%\..\build.vc\yasm\1.3.0\yasm.exe
          echo.
          echo "Run MSBuild"
          echo.
          MSBuild -m mpir.sln -p:useenv=false -p:Configuration=Release -p:Platform=x64 /t:Rebuild
          dir %CD%\..\lib\x64\Release
